/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <errno.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#ifndef _WIN32
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif


/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 64
#define YY_END_OF_BUFFER 65
static yyconst short int yy_accept[197] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       65,   63,    1,    2,    1,   34,   43,   28,   63,   24,
       37,   38,   27,   36,   27,   63,   28,   21,   35,   31,
       32,   31,   59,   41,   42,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   39,   63,   40,
       64,   49,   48,   49,   44,   49,   58,   57,   58,   58,
       54,   51,   54,   54,    1,    2,   31,   33,   24,   23,
       24,   29,   30,   22,   55,   50,   22,   21,   62,   62,
       59,   59,   59,   59,   59,   59,    7,   59,   59,   59,
        3,   59,   59,   59,   59,   59,   59,   59,   48,   47,

       46,   47,   45,   57,   56,   51,   53,   52,   53,    0,
       25,   24,   24,    0,   22,    0,   22,   62,    0,   22,
       59,   59,   59,   59,   59,   59,   59,   59,    5,    9,
       59,   59,   59,   59,   59,   59,   46,   52,    0,   26,
       25,   61,    0,   22,    0,   22,   22,   59,   16,   12,
       59,   59,   59,    4,   59,   19,   59,   59,   59,   14,
       59,   61,    0,   61,   22,   60,   22,   62,    8,   59,
       59,   59,   10,   59,   59,   59,    6,    0,    0,   22,
       60,   62,   59,   59,   11,   20,   13,   15,    0,   62,
       59,   17,    0,   62,   18,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,    8,   22,   23,
       24,   25,    8,    8,   26,   26,   26,   26,   27,   26,
       26,   26,   28,   26,   26,   28,   26,   28,   26,   26,
       26,   26,   26,   26,   26,   26,   28,   26,   26,   26,
       29,   30,   31,    8,   32,    8,   33,   34,   35,   36,

       37,   38,   26,   39,   40,   26,   41,   42,   43,   44,
       45,   46,   26,   47,   48,   49,   50,   51,   52,   26,
       26,   26,   53,   54,   55,    8,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[56] =
    {   0,
        1,    1,    1,    1,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    3,    2,    4,
        4,    2,    2,    2,    2,    4,    5,    5,    2,    2,
        2,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    6,    2,    6
    } ;

static yyconst short int yy_base[209] =
    {   0,
        0,    0,    0,    0,   53,   55,   60,   62,   64,   66,
      404,  405,   73,  405,   77,  379,  405,  405,  392,   60,
      405,  405,  386,  405,  383,   52,   70,   77,  405,  375,
      374,  373,    0,  405,  405,  349,   54,   55,  353,   46,
       63,  361,  291,  300,  284,  289,  294,  405,  278,  405,
      405,  405,  405,  328,  405,  112,  405,  405,  327,  309,
      405,  405,  323,   99,  104,  405,  405,  405,  313,  310,
      157,  405,  405,  100,  405,  405,  104,  133,    0,  113,
        0,  277,  265,  279,  265,  268,  254,  254,  256,  253,
        0,  240,  243,  238,  225,  225,  220,  219,  405,  405,

      405,  255,  405,  405,  405,  405,  405,  405,  251,  238,
      234,  229,  227,   90,  151,  123,  155,    0,   92,  137,
      204,  195,  183,  175,  186,  184,  180,  178,    0,    0,
      161,  158,  150,  150,  162,  151,  405,  405,  178,  175,
      174,  176,  189,  163,  194,  202,  207,  139,    0,    0,
      139,  124,  125,    0,  117,    0,  116,  115,  117,    0,
      112,  215,  226,  230,  235,  243,  248,  256,    0,  104,
      105,  102,    0,   91,   82,   78,    0,  115,  261,  266,
      270,  274,   55,   37,    0,    0,    0,    0,  278,  290,
       24,    0,  298,  302,    0,  405,  339,  345,  351,  357,

      362,  366,  368,  373,  377,  380,  383,  387
    } ;

static yyconst short int yy_def[209] =
    {   0,
      196,    1,  197,  197,  198,  198,  199,  199,  200,  200,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  201,
      196,  196,  196,  196,  196,  196,  196,  202,  196,  196,
      196,  196,  203,  196,  196,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  196,  196,  196,
      196,  196,  196,  196,  196,  204,  196,  196,  196,  196,
      196,  196,  196,  205,  196,  196,  196,  196,  206,  206,
      206,  196,  196,  196,  196,  196,  196,  202,  207,  207,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  196,  196,

      196,  196,  196,  196,  196,  196,  196,  196,  196,  208,
      208,  208,  208,  196,  196,  196,  196,  207,  196,  207,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  196,  196,  208,  208,
      208,  196,  196,  196,  196,  196,  207,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  196,  196,  196,  196,  196,  207,  207,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  196,  196,  196,
      196,  207,  203,  203,  203,  203,  203,  203,  196,  207,
      203,  203,  196,  207,  203,    0,  196,  196,  196,  196,

      196,  196,  196,  196,  196,  196,  196,  196
    } ;

static yyconst short int yy_nxt[461] =
    {   0,
       12,   13,   14,   15,   13,   16,   17,   12,   18,   19,
       20,   21,   22,   18,   23,   24,   25,   26,   27,   28,
       28,   29,   30,   31,   32,   33,   33,   33,   34,   12,
       35,   33,   33,   36,   37,   38,   39,   40,   33,   41,
       33,   33,   42,   33,   33,   43,   44,   45,   33,   33,
       46,   47,   48,   49,   50,   53,   54,   53,   54,   55,
      195,   55,   58,   59,   58,   59,   62,   63,   62,   63,
       70,   74,   74,   60,   65,   60,   65,   65,   65,   66,
       65,   65,   56,   75,   56,  192,   83,   89,   76,   71,
       90,   86,   84,   64,   77,   64,   78,   78,   85,   87,

       91,  108,  109,   80,  191,   65,   92,   65,   65,  142,
      142,  144,  144,   80,  101,  102,  188,  114,  103,  115,
      115,  114,  103,  117,  117,  187,  116,  119,  186,  119,
      116,  103,  120,  120,  179,  179,  116,  119,  185,  119,
      116,  103,  144,  144,  103,  103,  184,  183,  177,  103,
       77,  176,   78,   78,  114,  103,  147,  147,  103,   80,
      103,  175,  103,  112,  174,  173,  172,  113,  143,   80,
      115,  115,  145,  171,  146,  146,  112,  116,  170,  169,
      114,  116,  165,  165,  140,  140,  112,  116,  140,  112,
      112,  116,  161,  114,  112,  162,  162,  160,  159,  158,

      112,  157,  163,  112,  156,  112,  114,  112,  164,  164,
      155,  114,  163,  166,  166,  163,  154,  153,  152,  145,
      163,  146,  146,  151,  143,  163,  167,  167,  116,  150,
      163,  149,  143,  168,  162,  162,  148,  141,  116,  141,
      178,  163,  178,  168,  140,  179,  179,  143,  140,  162,
      162,  163,  143,  138,  180,  180,  163,  137,  136,  135,
      145,  163,  181,  181,  134,  143,  163,  167,  167,  163,
      178,  163,  178,  133,  168,  182,  182,  132,  114,  163,
      189,  189,  131,  143,  168,  180,  180,  145,  130,  181,
      181,  114,  163,  190,  190,  143,  163,  193,  193,  129,

      128,  127,  163,  126,  163,  125,  163,  143,  124,  194,
      194,  123,  122,  121,  163,  143,  168,  193,  193,  143,
      111,  194,  194,  111,  163,  106,  168,  105,  168,  104,
       99,   68,   98,   97,  163,   96,   95,   94,  168,   51,
       51,   51,   51,   51,   51,   52,   52,   52,   52,   52,
       52,   57,   57,   57,   57,   57,   57,   61,   61,   61,
       61,   61,   61,   69,   69,   69,   69,   69,   79,   79,
       79,   81,   81,  100,  100,  100,  100,  107,  107,  107,
      107,  110,  110,  110,  110,  110,  118,  118,  139,  139,
      139,  139,  139,   93,   88,   82,   67,   67,   67,   73,

       72,   68,   67,  196,   11,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196
    } ;

static yyconst short int yy_chk[461] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    5,    6,    6,    5,
      191,    6,    7,    7,    8,    8,    9,    9,   10,   10,
       20,   26,   26,    7,   13,    8,   13,   13,   15,   15,
       15,   15,    5,   27,    6,  184,   37,   40,   27,   20,
       40,   38,   37,    9,   28,   10,   28,   28,   37,   38,

       41,   64,   64,   28,  183,   65,   41,   65,   65,  114,
      114,  119,  119,   28,   56,   56,  176,   74,   56,   74,
       74,   77,   56,   77,   77,  175,   74,   80,  174,   80,
       77,   56,   80,   80,  178,  178,   74,  116,  172,  116,
       77,   56,  116,  116,   56,   56,  171,  170,  161,   56,
       78,  159,   78,   78,  120,   56,  120,  120,   56,   78,
       56,  158,   56,   71,  157,  155,  153,   71,  115,   78,
      115,  115,  117,  152,  117,  117,   71,  115,  151,  148,
      144,  117,  144,  144,  141,  140,   71,  115,  139,   71,
       71,  117,  136,  142,   71,  142,  142,  135,  134,  133,

       71,  132,  142,   71,  131,   71,  143,   71,  143,  143,
      128,  145,  142,  145,  145,  143,  127,  126,  125,  146,
      145,  146,  146,  124,  147,  143,  147,  147,  146,  123,
      145,  122,  162,  147,  162,  162,  121,  113,  146,  112,
      163,  162,  163,  147,  111,  163,  163,  164,  110,  164,
      164,  162,  165,  109,  165,  165,  164,  102,   98,   97,
      166,  165,  166,  166,   96,  167,  164,  167,  167,  166,
      168,  165,  168,   95,  167,  168,  168,   94,  179,  166,
      179,  179,   93,  180,  167,  180,  180,  181,   92,  181,
      181,  182,  180,  182,  182,  189,  181,  189,  189,   90,

       89,   88,  180,   87,  189,   86,  181,  190,   85,  190,
      190,   84,   83,   82,  189,  193,  190,  193,  193,  194,
       70,  194,  194,   69,  193,   63,  190,   60,  194,   59,
       54,   49,   47,   46,  193,   45,   44,   43,  194,  197,
      197,  197,  197,  197,  197,  198,  198,  198,  198,  198,
      198,  199,  199,  199,  199,  199,  199,  200,  200,  200,
      200,  200,  200,  201,  201,  201,  201,  201,  202,  202,
      202,  203,  203,  204,  204,  204,  204,  205,  205,  205,
      205,  206,  206,  206,  206,  206,  207,  207,  208,  208,
      208,  208,  208,   42,   39,   36,   32,   31,   30,   25,

       23,   19,   16,   11,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "analyzer.l"
#define INITIAL 0
#define UNKNOWN_WORD 1

#define STRING_STATE 2

#define MULTILINE_CMNT_STATE 3

#define SINGLELINE_CMNT_STATE 4

#line 11 "analyzer.l"
#include "SymbolInfo.h"
#include "y.tab.h"

// #define YYSTYPE SymbolInfo*
extern YYSTYPE yylval;

int lineCount=1;
int wordCount=0;
int errorCount=0;
int logStringStart;

string tokenString="";
string logString="";
string newString="";


extern FILE *logout;
extern FILE *errorout;
FILE *tokenout;

void yyerror(char *);

void increaseWordCount(){
	wordCount++;
}

void increaseErrorCount(){
	errorCount++;
}

char* toUpper(char *s){
    int i;
    char* u= new char;
    for (i = 0; s[i]!='\0'; i++) {
      if(s[i] >= 'a' && s[i] <= 'z') {
         u[i] = s[i]-32;
      } else u[i]=s[i];
   }
   return u;
}

char toSpecial(char* s){
	char sp;
	if(s[0]=='\\'){
		if(s[1]=='n') sp='\n';
		if(s[1]=='t') sp='\t';
		if(s[1]=='\\') sp='\\';
		if(s[1]=='\'') sp='\'';
		if(s[1]=='a') sp='\a';
		if(s[1]=='f') sp='\f';
		if(s[1]=='r') sp='\r';
		if(s[1]=='b') sp='\b';
		if(s[1]=='v') sp='\v';
		if(s[1]=='0') sp='\0';
		if(s[1]=='\"') sp='\"';
		return sp;
	}
	if(s[1]!= '\\') sp=s[1];
	else {
		if(s[2]=='n') sp='\n';
		if(s[2]=='t') sp='\t';
		if(s[2]=='\\') sp='\\';
		if(s[2]=='\'') sp='\'';
		if(s[2]=='a') sp='\a';
		if(s[2]=='f') sp='\f';
		if(s[2]=='r') sp='\r';
		if(s[2]=='b') sp='\b';
		if(s[2]=='v') sp='\v';
		if(s[2]=='0') sp='\0';
		if(s[1]=='\"') sp='\"';
	}
	return sp;
}



void detectKeyword(char *str){
    char* s= toUpper(str);
    // fprintf(tokenout,"<%s> ",s);
	// fprintf(logout,"Line no %d: Token <%s> Lexeme %s found\n\n",lineCount,s,str);
	// increaseWordCount();
	
}

void detectUnknownWord(char *str){
	increaseErrorCount();
	// printf("Unknown word %s\n", str);
	// fprintf(logout,"Error at line no %d: Unrecognized word %s\n\n",lineCount,str);
}

void endOfFile(){
	string allScope;
	// allScope=table->printAllScope();
	// fprintf(logout,"%s",allScope.c_str());
	// fprintf(logout,"Total lines: %d\n",lineCount);
	// fprintf(logout,"Total errors: %d\n",errorCount);
}

#line 644 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 134 "analyzer.l"


#line 809 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 197 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 405 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 136 "analyzer.l"
{}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 138 "analyzer.l"
{lineCount++;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 140 "analyzer.l"
{return IF;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 141 "analyzer.l"
{return ELSE;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 142 "analyzer.l"
{return FOR;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 143 "analyzer.l"
{return WHILE;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 144 "analyzer.l"
{return DO;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 145 "analyzer.l"
{return BREAK;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 146 "analyzer.l"
{return INT;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 147 "analyzer.l"
{return FLOAT;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 148 "analyzer.l"
{return DOUBLE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 149 "analyzer.l"
{return CHAR;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 150 "analyzer.l"
{return RETURN;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 151 "analyzer.l"
{return VOID;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 152 "analyzer.l"
{return SWITCH;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 153 "analyzer.l"
{return CASE;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 154 "analyzer.l"
{return DEFAULT;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 155 "analyzer.l"
{return CONTINUE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 156 "analyzer.l"
{return MAIN;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 157 "analyzer.l"
{return PRINTLN;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 159 "analyzer.l"
{
	// fprintf(tokenout,"<CONST_INT, %s> ", yytext);
	// fprintf(logout,"Line no %d: Token <CONST_INT> Lexeme %s found\n\n",lineCount,yytext);
	SymbolInfo *s= new  SymbolInfo(yytext, "CONST_INT");
	yylval.symbol = s;
	return CONST_INT;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 167 "analyzer.l"
{
	// fprintf(tokenout,"<CONST_FLOAT, %s> ", yytext);
	// fprintf(logout,"Line no %d: Token <CONST_FLOAT> Lexeme %s found\n\n",lineCount,yytext);
	SymbolInfo *s= new  SymbolInfo(yytext, "CONST_FLOAT");
	yylval.symbol = s;
	return CONST_FLOAT;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 175 "analyzer.l"
{
	increaseErrorCount();
	// fprintf(logout,"Error at line no %d: Empty character constant error \'\'\n\n",lineCount);
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 180 "analyzer.l"
{
	increaseErrorCount();
	// fprintf(logout,"Error at line no %d: Unterminated character %s\n\n",lineCount,yytext);
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 185 "analyzer.l"
{
	char ch= toSpecial(yytext);
	// fprintf(tokenout,"<CONST_CHAR, %c> ", ch);
	// fprintf(logout,"Line no %d: Token <CONST_CHAR> Lexeme %s found --> <CONST_CHAR, %c> \n\n",lineCount,yytext,ch);
	
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 192 "analyzer.l"
{
	increaseErrorCount();
	// fprintf(logout,"Error at line no %d: Multi character constant error %s\n\n",lineCount,yytext);
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 197 "analyzer.l"
{
	// fprintf(tokenout,"<ADDOP,%s> ",yytext);
	// fprintf(logout,"Line no %d: Token <ADDOP> Lexeme %s found\n\n",lineCount,yytext);
	SymbolInfo *s= new  SymbolInfo(yytext, "ADDOP");
	yylval.symbol = s;
	return ADDOP;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 205 "analyzer.l"
{
	// fprintf(tokenout,"<MULOP,%s> ",yytext);
	// fprintf(logout,"Line no %d: Token <MULOP> Lexeme %s found\n\n",lineCount,yytext);
	SymbolInfo *s= new  SymbolInfo(yytext, "MULOP");
	yylval.symbol = s;
	return MULOP;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 213 "analyzer.l"
{return INCOP;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 214 "analyzer.l"
{return DECOP;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 216 "analyzer.l"
{
	// fprintf(tokenout,"<RELOP,%s> ",yytext);
	// fprintf(logout,"Line no %d: Token <RELOP> Lexeme %s found\n\n",lineCount,yytext);
	SymbolInfo *s= new  SymbolInfo(yytext, "RELOP");
	yylval.symbol = s;
	return RELOP;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 224 "analyzer.l"
{
	// fprintf(tokenout,"<ASSIGNOP,%s> ",yytext);
	// fprintf(logout,"Line no %d: Token <ASSIGNOP> Lexeme %s found\n\n",lineCount,yytext);
	return ASSIGNOP;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 230 "analyzer.l"
{
	// fprintf(tokenout,"<LOGICOP,%s> ",yytext);
	// fprintf(logout,"Line no %d: Token <LOGICOP> Lexeme %s found\n\n",lineCount,yytext);
	SymbolInfo *s= new  SymbolInfo(yytext, "LOGICOP");
	yylval.symbol = s;
	return LOGICOP;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 238 "analyzer.l"
{
	// fprintf(tokenout,"<NOT,%s> ",yytext);
	// fprintf(logout,"Line no %d: Token <NOT> Lexeme %s found\n\n",lineCount,yytext);
	return NOT;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 244 "analyzer.l"
{ return SEMICOLON;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 245 "analyzer.l"
{return COMMA;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 246 "analyzer.l"
{return LPAREN;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 247 "analyzer.l"
{return RPAREN;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 248 "analyzer.l"
{return LCURL;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 249 "analyzer.l"
{return RCURL;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 250 "analyzer.l"
{return LTHIRD;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 251 "analyzer.l"
{return RTHIRD;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 253 "analyzer.l"
{
	BEGIN STRING_STATE;
	logStringStart=lineCount;
	newString=yytext;
	tokenString.append(newString);
	logString.append(newString);
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 261 "analyzer.l"
{
	newString=yytext;
	tokenString.append(newString);
	logString.append(newString);
	// fprintf(tokenout,"<STRING,%s> ",tokenString.c_str());
	// fprintf(logout,"Line no %d: Token <STRING> Lexeme %s found --> <STRING,%s> \n\n",logStringStart,logString.c_str(),tokenString.c_str());
	BEGIN INITIAL;
	tokenString="";
	logString="";
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 272 "analyzer.l"
{
	newString=yytext;
	logString.append(newString);
	char ch= toSpecial(yytext);
	// printf("%c", ch);
	newString= ch;
	tokenString.append(newString);	
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 281 "analyzer.l"
{
	lineCount++;
	newString=yytext;
	logString.append(newString);
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 287 "analyzer.l"
{
	increaseErrorCount();
	newString=yytext;
	logString.append(newString);
	// fprintf(logout,"Error at line no %d: Unterminated String %s\n\n",logStringStart,logString.c_str());
	BEGIN INITIAL;
	tokenString="";
	logString="";
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 297 "analyzer.l"
{
	lineCount++;
	increaseErrorCount();
	// logString.append(newString);
	// fprintf(logout,"Error at line no %d: Unterminated String %s\n\n",logStringStart,logString.c_str());
	BEGIN INITIAL;
	tokenString="";
	logString="";
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 307 "analyzer.l"
{
	newString=yytext;
	tokenString.append(newString);
	logString.append(newString);
}
	YY_BREAK
case YY_STATE_EOF(STRING_STATE):
#line 313 "analyzer.l"
{
	increaseErrorCount();
	// fprintf(logout,"Error at line no %d: Unterminated String %s\n\n",logStringStart,logString.c_str());
	BEGIN INITIAL;
	tokenString="";
	logString="";
	endOfFile();
	return 0;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 323 "analyzer.l"
{
	BEGIN SINGLELINE_CMNT_STATE;
	logStringStart=lineCount;
	newString=yytext;
	logString.append(newString);
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 330 "analyzer.l"
{
	lineCount++;
	// fprintf(logout,"Line no %d: Token <COMMENT> Lexeme %s found\n\n",logStringStart,logString.c_str());
	BEGIN INITIAL;
	logString="";
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 337 "analyzer.l"
{
	lineCount++;
	newString=yytext;
	logString.append(newString);
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 343 "analyzer.l"
{
	newString=yytext;
	logString.append(newString);
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 348 "analyzer.l"
{
	newString=yytext;
	logString.append(newString);
}
	YY_BREAK
case YY_STATE_EOF(SINGLELINE_CMNT_STATE):
#line 353 "analyzer.l"
{
	// fprintf(logout,"Line no %d: Token <COMMENT> Lexeme %s found\n\n",logStringStart,logString.c_str());
	BEGIN INITIAL;
	tokenString="";
	logString="";
	endOfFile();
	return 0;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 362 "analyzer.l"
{
	BEGIN MULTILINE_CMNT_STATE;
	logStringStart=lineCount;
	newString=yytext;
	logString.append(newString);
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 369 "analyzer.l"
{
	BEGIN INITIAL;
	newString=yytext;
	logString.append(newString);
	// fprintf(logout,"Line no %d: Token <COMMENT> Lexeme %s found\n\n",logStringStart,logString.c_str());
	logString="";
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 377 "analyzer.l"
{
	lineCount++;
	newString=yytext;
	logString.append(newString);
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 384 "analyzer.l"
{
	newString=yytext;
	logString.append(newString);
}
	YY_BREAK
case YY_STATE_EOF(MULTILINE_CMNT_STATE):
#line 389 "analyzer.l"
{
	BEGIN INITIAL;
	increaseErrorCount();
	// fprintf(logout,"Error at line no %d: Unterminated comment %s\n\n",logStringStart,logString.c_str());
	endOfFile();
	return 0;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 397 "analyzer.l"
{
	// fprintf(tokenout,"<ID,%s> ",yytext);
	// fprintf(logout,"Line no %d: Token <ID> Lexeme %s found\n\n",lineCount,yytext);
	SymbolInfo *s= new  SymbolInfo(yytext, "ID");
	// cout<<*s<<endl;
	yylval.symbol = s;
	return ID;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 406 "analyzer.l"
{
	increaseErrorCount();
	// fprintf(logout,"Error at line no %d: Too many decimal points %s\n\n",lineCount,yytext);
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 411 "analyzer.l"
{
	increaseErrorCount();
	// fprintf(logout,"Error at line no %d: Ill formed number %s\n\n",lineCount,yytext);
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 416 "analyzer.l"
{
	increaseErrorCount();
	// fprintf(logout,"Error at line no %d: Invalid prefix on ID or invalid suffix on Number %s\n\n",lineCount,yytext);
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 421 "analyzer.l"
{
	increaseErrorCount();
	// fprintf(logout,"Error at line no %d: Unrecognized character %s\n\n",lineCount,yytext);
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(UNKNOWN_WORD):
#line 426 "analyzer.l"
{
	endOfFile();
	return 0;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 432 "analyzer.l"
ECHO;
	YY_BREAK
#line 1414 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 197 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 197 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 196);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef _WIN32
#include <unistd.h>
#else
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 432 "analyzer.l"



